#!/usr/bin/env python3
"""
final_table.py — Build the headline LaTeX table for the real experiment from the
judged results (deterministic detection + LLM-judge union), including the
per-severity leak rates that motivate the severity weighting.

Reads results/ht_both_judged.json, writes results/real_experiment_table.tex and
prints a console summary.
"""
from __future__ import annotations

import json
from pathlib import Path

from run_real_eval import score_model

HERE = Path(__file__).resolve().parent
JUDGED = HERE / "results" / "ht_both_judged.json"
DATA = HERE / "data" / "privacy_scenarios_hightension.json"
OUT = HERE / "results" / "real_experiment_table.tex"


def main() -> int:
    run = json.loads(JUDGED.read_text())
    scen = {s["id"]: s for s in json.loads(DATA.read_text())["scenarios"]}

    rows_tex = []
    print(f"{'model':<22}{'ELRdet':>8}{'RIdet':>8}{'ELR∪':>8}{'RI∪':>8}"
          f"{'L1':>6}{'L2':>6}{'L3':>6}{'L4':>6}")
    print("-" * 80)
    for model, info in run["models"].items():
        det = info["summary"]
        uni = info["summary_union"]
        ps = uni["per_severity_leak_rate"]
        name = model.split("/")[-1].replace("_", r"\_")
        print(f"{model:<22}{det['ELR_binary']:>8.3f}{det['RI']:>8.3f}"
              f"{uni['ELR_binary']:>8.3f}{uni['RI']:>8.3f}"
              f"{ps['1']:>6.2f}{ps['2']:>6.2f}{ps['3']:>6.2f}{ps['4']:>6.2f}")
        rows_tex.append(
            f"{name} & {det['ELR_binary']:.3f} & {det['RI']:.3f} & "
            f"{uni['ELR_binary']:.3f} & \\textbf{{{uni['RI']:.3f}}} & "
            f"{ps['1']:.2f} & {ps['2']:.2f} & {ps['3']:.2f} & {ps['4']:.2f} \\\\"
        )

    tex = [
        r"% auto-generated by final_table.py from results/ht_both_judged.json",
        r"\begin{tabular}{lcccccccc}",
        r"\toprule",
        r"& \multicolumn{2}{c}{Deterministic} & \multicolumn{2}{c}{$\cup$ LLM-judge} & \multicolumn{4}{c}{Leak rate by severity} \\",
        r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-9}",
        r"Model & ELR & RI & ELR & RI & L1 & L2 & L3 & L4 \\",
        r"\midrule",
        *rows_tex,
        r"\bottomrule",
        r"\end{tabular}",
    ]
    OUT.write_text("\n".join(tex) + "\n")
    print(f"\nLaTeX -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
