#!/usr/bin/env python3
"""
meta_analysis.py — Cross-framework comparison of *published* privacy-leakage
numbers. Every value here is transcribed from a primary source (arXiv / paper)
and is cited; NOTHING is fabricated or re-estimated.

Purpose: show (a) that the field reports privacy failure almost exclusively as
an *unweighted binary* rate, and (b) the spread of those rates across recent
agent-privacy benchmarks. AgentRisk's severity weighting is NOT retro-fitted to
these numbers, because none of these papers publish a per-severity breakdown;
the severity-weighted evidence comes from our own end-to-end experiment
(run_real_eval.py).

Emits a LaTeX table fragment to results/meta_comparison.tex.
"""
from __future__ import annotations

from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT_TEX = HERE / "results" / "meta_comparison.tex"

# Each entry: framework, model/condition, published binary leakage metric (%),
# what the metric measures, citation key (matches references.bib), verbatim note.
PUBLISHED = [
    # --- AgentDAM (arXiv:2503.09780, NeurIPS 2025 D&B) ---
    ("AgentDAM", "GPT-4o",            43.5, "privacy leakage rate (axtree)",        "agentdam"),
    ("AgentDAM", "GPT-4o-mini",       29.7, "privacy leakage rate (axtree)",        "agentdam"),
    ("AgentDAM", "GPT-4-turbo",       45.5, "privacy leakage rate (axtree)",        "agentdam"),
    ("AgentDAM", "Llama-3.2-90B",     33.3, "privacy leakage rate (axtree)",        "agentdam"),
    ("AgentDAM", "Llama-3.3-70B",     40.2, "privacy leakage rate (axtree)",        "agentdam"),
    ("AgentDAM", "Claude-CUA",        35.0, "privacy leakage rate (screenshot)",    "agentdam"),
    # --- MAGPIE (arXiv:2506.20737) ---
    ("MAGPIE", "GPT-4o (misclassify)",      25.2, "marks private data shareable", "magpie"),
    ("MAGPIE", "Claude-3.7 (misclassify)",  43.6, "marks private data shareable", "magpie"),
    ("MAGPIE", "GPT-4o (discloses)",        59.9, "leaks under explicit privacy instr.", "magpie"),
    ("MAGPIE", "Claude-3.7 (discloses)",    50.5, "leaks under explicit privacy instr.", "magpie"),
    # --- AgentLeak (local source) ---
    ("AgentLeak", "C1 (direct request)",  27.2, "channel leak rate",  "agentleak"),
    ("AgentLeak", "C2 (tool/API trace)",  68.8, "channel leak rate",  "agentleak"),
    ("AgentLeak", "C5 (multi-hop)",       46.7, "channel leak rate",  "agentleak"),
    ("AgentLeak", "H1 (output-only miss)",41.7, "audit blind spot",   "agentleak"),
]


def main() -> int:
    vals = [p[2] for p in PUBLISHED]
    print(f"Published binary leakage rates across {len({p[0] for p in PUBLISHED})} "
          f"frameworks, {len(PUBLISHED)} conditions.")
    print(f"  range: {min(vals):.1f}% - {max(vals):.1f}%   mean: {sum(vals)/len(vals):.1f}%")
    print("  NOTE: all are UNWEIGHTED binary rates; none report per-severity weighting.")

    lines = [
        r"% auto-generated by meta_analysis.py (all values cited, none fabricated)",
        r"\begin{tabular}{llrl}",
        r"\toprule",
        r"Framework & Model / condition & Rate (\%) & Metric \\",
        r"\midrule",
    ]
    cur = None
    for fw, cond, rate, metric, cite in PUBLISHED:
        fwcell = ""
        if fw != cur:
            if cur is not None:
                lines.append(r"\midrule")
            fwcell = f"{fw}~\\cite{{{cite}}}"
            cur = fw
        lines.append(f"{fwcell} & {cond} & {rate:.1f} & {metric} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    OUT_TEX.write_text("\n".join(lines) + "\n")
    print(f"LaTeX table -> {OUT_TEX}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
